version: '3'
services:
  nebraska:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: |
      sh -c '
        sleep 3
        /nebraska/nebraska -http-static-dir=/nebraska/static'
    depends_on:
      - "postgres"
  postgres:
    image: quay.io/flatcar/nebraska-postgres
    volumes:
      - postgres-data:/nebraska/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
